apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "teams-msgs.labels" . | nindent 4 }}
    {{- if .Values.istio.enabled }}
    istio-injection: {{ .Values.istio.injectionLabel | quote }}
    {{- end }}
