apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teams-msgs.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "teams-msgs.labels" . | nindent 4 }}
type: Opaque
stringData:
  Api__ApiKey: {{ .Values.api.apiKey | quote }}
  Storage__ConnectionString: {{ .Values.storage.connectionString | quote }}
  ServiceBus__ConnectionString: {{ .Values.serviceBus.connectionString | quote }}
  Redis__ConnectionString: {{ .Values.redis.connectionString | quote }}
  Bot__AppPassword: {{ .Values.bot.appPassword | quote }}
  MicrosoftAppPassword: {{ .Values.bot.appPassword | quote }}
