apiVersion: v1
kind: ServiceAccount
metadata:
  name: teams-msgs-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "teams-msgs.api.labels" . | nindent 4 }}
  {{- if .Values.workloadIdentity.enabled }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.uamiClientId | quote }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: teams-msgs-worker
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "teams-msgs.worker.labels" . | nindent 4 }}
  {{- if .Values.workloadIdentity.enabled }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.uamiClientId | quote }}
  {{- end }}
